### ISSUE TITLE
stuck on ruby variable types

### ISSUE THREAD

**Issue by seanreed1111** [learn-co-curriculum/ruby-variable-types-readme#4]
I am using chrome on this and I don't see any buttons on the RHS of the page that allow me to move forward after reading the text on the page.

**Comment by AnnJohn** [comment]
hi @seanreed1111 this looks like a technical bug. Could you please use the Ask a Question tool and someone from our team will get back to you? Could you also file a bug report? If you hover over your profile pic in Learn, a menu will pop up with one being to Report a Bug. Thanks!
